# Generated by Django 3.1.1 on 2020-11-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201113_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart_json',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recentSearch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommendedProduct',
        ),
    ]
